version: '3.7'

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_db
    volumes:
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
